name: Test

on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn
      - name: Check Svelte
        run: yarn svelte-check
        working-directory: packages/ui
      - name: Run tests
        run: yarn test
        working-directory: packages/core
